# Generated by Django 2.2.27 on 2022-04-03 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('sexe', models.CharField(max_length=10)),
                ('dateNaissance', models.IntegerField(null=True)),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('lieuResidance', models.CharField(max_length=100)),
                ('NumTel1', models.IntegerField(null=True)),
                ('NumTel2', models.IntegerField(null=True)),
                ('Assurance', models.CharField(max_length=45)),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
