# Generated by Django 3.2.3 on 2022-06-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_consultation_resultatconsultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='secretaire',
            new_name='medecin',
        ),
    ]
