# Generated by Django 3.2.3 on 2022-06-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_rename_medecin_rendevous_medecin_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rendevous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.rendevous'),
        ),
    ]
